# INTEL CONFIDENTIAL
#
# Copyright 2019-2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
- name: disable dns if openness is not enabled
  set_fact:
    dns_enable: false
  when: not (openness_enable | default(false))

- name: enable or disable certificate signer/requester
  set_fact:
    cert_enabled: "{{ (openness_enable or dns_enable ) | bool }}"
    _gitconfig_bootstrap_path: "{{ role_path }}/../../../../opendek/roles/baseline_ansible/infrastructure/git_repo/tasks/gitconfig_bootstrap.yml"
    _gitconfig_remove_path: "{{ role_path }}/../../../../opendek/roles/baseline_ansible/infrastructure/git_repo/tasks/gitconfig_remove.yml"
