# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---

- name: Restart the sriov-device-plugin pod
  block:
  - name: Get the name of sriov-device-plugin pod
    shell: kubectl get pods -n kube-system | grep .*sriov-device-plugin | awk '{ print $1 }'
    register: sriov_device_plugin_pod_names
  - name: Delete sriov-device-plugin pod
    command: kubectl delete pod -n kube-system {{ item }}
    loop: "{{ sriov_device_plugin_pod_names.stdout_lines }}"
  - name: Get the name of sriov-device-plugin pod after deletion
    shell: kubectl get pods -n kube-system | grep .*sriov-device-plugin | awk '{ print $1 }'
    register: sriov_device_plugin_pods
  - name: Verify the sriov-device-plugins has been restarted
    shell: kubectl get pods -n kube-system | grep .*{{ item }}
    register: sriov_device_plugin_pod_restarted
    until: sriov_device_plugin_pod_restarted.stdout.find("Running") != -1
    retries: 30
    delay: 10
    loop: "{{ sriov_device_plugin_pods.stdout_lines }}"
