# INTEL CONFIDENTIAL
#
# Copyright 2020-2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
##Path to offline download
_offline_package_images: "{{ pwek_offline_package_path }}/controller/images"
_offline_package_charts: "{{ pwek_offline_package_path }}/controller/charts"

# DPDK driver used (vfio-pci/igb_uio) to VFs bindings
app_name: "pwek-5gc"

#dpdk_driver_upf: "igb_uio"
#edgeapps_git_repo:  #need remove
#  dest: "/opt/edgeapps"  #need remove

# Paths for storing pwek related resources
pwek_charts_path: "{{ remote_pwek_path }}/charts/"
pwek_images_path: "{{ remote_pwek_path }}/images/"
pwek_scripts_path: "{{ remote_pwek_path }}/scripts/"
pwek_dpdk_path: "{{ remote_pwek_path }}/dpdk-19.11"

# 5gc docker image source type
5gc_docker_image_source: "import"

# 5GC upf, amf, smf version
amf_version: "v1"
oamamf_version: "latest"
smf_version: "v1"
oamsmf_version: "latest"
upf_version: "v2.3.2"
oamupf_version: "latest"
