# Copyright (C) 2021  Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hvs-db-chart.name" . }}-config
  namespace: {{ .Values.namespace }}
data:
  pg_hba.conf:
    {{- toYaml .Values.postgresConf.hbaConf | nindent 4 }}
  postgresql.conf:
    {{- toYaml .Values.postgresConf.sqlConf | nindent 4 }}
