# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "hvs-db-chart.name" . }}-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolumeConfig.storage }}
  volumeMode: {{ .Values.persistentVolumeConfig.volumeMode }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: {{ .Values.persistentVolumeConfig.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.persistentVolumeConfig.storageClassName }}
  nfs:
    path: {{ .Values.persistentVolumeConfig.nfs.path }}
    server: {{ .Values.persistentVolumeConfig.nfs.server }}
