# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hvs-db-chart.name" . }}-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.persistentVolumeConfig.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentVolumeConfig.storage }}
