# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.container.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- toYaml .Values.container.args | nindent 12 }}
          ports:
            - containerPort: {{ .Values.container.containerPort }}
          env:
            {{- toYaml .Values.environment | nindent 12 }}
          volumeMounts:
            - name: hvs-db-config
              mountPath: {{ .Values.volumeConfig.hvsDbConfigPath }}
            - name: hvs-db-certs
              mountPath: {{ .Values.volumeConfig.hvsDbCertsPath }}
            - name: hvs-db-data
              mountPath: {{ .Values.volumeConfig.hvsDbDataPath }}
      volumes:
        - name: hvs-db-config
          configMap:
            name: hvs-db-config
            defaultMode: 0640
        - name: hvs-db-certs
          secret:
            secretName: hvs-db-certs
            defaultMode: 0640
        - name: hvs-db-data
          persistentVolumeClaim:
            claimName: hvs-db-pvc

