# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "hvs-db-chart.name" . }}-credentials
  namespace: {{ .Values.namespace }}
stringData:
  {{- toYaml .Values.dbSecrets | nindent 2 }}
