# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
- name: include common vars
  include_vars: ../../common/defaults/main.yml

- name: make sure edge-agents, certs and configs directories exists
  file:
    path: "{{ item }}"
    state: directory
    mode: a=rwx
    owner: "{{ ansible_user }}"
    group: "{{ project_group }}"
  with_items:
    - "{{ agents_dir }}"
    - "{{ _certs_dest }}"
    - "{{ _configs_dest }}"
  become: yes

- name: copy configs
  copy:
    src: "{{ _edge_agents_git_repo.download_dir }}/edgedns/configs/edgedns_certrequest.json"
    dest: "{{ _configs_dest }}/"
    mode: preserve
    directory_mode: true
    remote_src: true

- name: customize Certificate Requester configs
  block:
    - name: include node name in EdgeDNS CSR name
      shell: jq '.CSR.Name="edgedns-{{ node_name }}"' '{{ _configs_dest }}/edgedns_certrequest.json' | sponge '{{ _configs_dest }}/edgedns_certrequest.json'

- name: create edgedns certificate directories
  file:
    path: "{{ item.dir }}"
    state: directory
    mode: a=rwx
    owner: "{{ item.owner }}"
    group: '1001'
  loop:
    - {dir: "{{ _certs_dest }}/edgedns", owner: 1006}
  become: yes

- name: build edgedns
  include_tasks: build.yml
