# INTEL CONFIDENTIAL
#
# Copyright 2020-2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
- hosts: controller_group
  pre_tasks:
    - name: Set global variables for baseline ansible
      set_fact:
        project_user: "{{ ansible_user }}"

    - name: set deployment varibale
      include_vars: "inventory/default/group_vars/all/10-open.yml"

    - name: set config varibale
      include_vars: "deployments/pwek-all-in-one/all.yml"

    - name: set config varibale
      include_vars: "opendek/roles/baseline_ansible/kubernetes/operator/sriov_network_operator/defaults/main.yml"

    - name: clean network
      command: kubectl delete -f  ./
      args:
        chdir: "{{ _sriov_network_config_dir }}"
      ignore_errors: true

    - name: clean files
      file:
       state: absent
       path: "{{ _sriov_network_config_dir }}"

  roles:
    - role: opendek/roles/baseline_ansible/kubernetes/operator/sriov_network_operator/configure
      when: "sriov_network_operator_enable and sriov_network_operator_configure_enable | default(False)"
