# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
- hosts: edgenode_group
  tasks:
    - name: pwek_gnodeb cleanup
      block:
      - name: load gnodeb variables
        include_vars: "{{ role_path }}/defaults/main.yml"
      - name: pwek_gnodeb cleanup
        include_tasks: "{{ role_path }}/tasks/cleanup.yml"
      vars:
        - role_path: "{{ playbook_dir }}/roles/applications/pwek_gnodeb"
      when: pwek_gnodeb_enable | default(False)

- hosts: controller_group
  tasks:
    - name: pwek_5gc cleanup
      block:
      - name: load 5gc variables
        include_vars: "{{ role_path }}/defaults/main.yml"
      - name: pwek_5gc cleanup
        include_tasks: "{{ role_path }}/tasks/cleanup.yml"
      vars:
        - role_path: "{{ playbook_dir }}/roles/applications/pwek_5gc"
      when: pwek_5gc_enable | default(False)
