# INTEL CONFIDENTIAL
#
# Copyright 2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---

- hosts: controller_group:edgenode_group
  any_errors_fatal: true

  tasks:
    - block:
      - name: include readiness tasks
        include: ./opendek/tasks/readiness_tasks.yml

      - block:
        - name: ngc readiness check
          include_tasks: ./roles/applications/ngc/controlplane/tasks/readiness.yml
          when:
            - "'controller_group' in group_names"
            - ne_ngc_enable | default(False)
        tags: ngc

      - block:
        - name: cellular-agent readiness check
          include_tasks: ./roles/agents/cellular-agent/cellularagent/tasks/readiness.yml
          when:
            - "'controller_group' in group_names"
            - cellularagent_enable | default(False)

      - block:
        - name: deployment agent readiness check
          include_tasks: ./roles/agents/deployment_agent/agent/tasks/readiness.yml
          when:
            - "'controller_group' in group_names"
            - da_enable | default(False)
        tags: deployment_agent

      - block:
        - name: deployment agent operator readiness check
          include_tasks: ./roles/agents/deployment_agent/operator/tasks/readiness.yml
          when:
            - "'controller_group' in group_names"
            - da_enable | default(False)

      - block:
        - name: edgedns readiness check
          include_tasks: ./roles/agents/edgedns/controlplane/tasks/readiness.yml
          when:
            - "'controller_group' in group_names"
            - "dns_enable | default(False)"
        tags: edgedns

      - block:
        - name: nsm readiness check
          include_tasks: ./roles/kubernetes/nsm/tasks/readiness.yml
          when:
            - "'controller_group' in group_names"
            - ne_nsm_enable | default(False)
        tags: nsm

      rescue:
        - block:
          - name: Call log collector
            include_tasks: ./opendek/tasks/collect_logs.yml
            when: collect_logs_after_failure | default(True)

          - name: propagate failure
            fail:
              msg: |
                Issues were found. Check logs of this playbook's execution for reason.
                Gathered logs are in the archive: {{ log_filename }}
          tags: always
