# Copyright (C) 2021  Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appName }}-config
  namespace: {{ .Values.namespace }}
data:
  nats.conf:
    {{- toYaml .Values.natsConfig.natsConf | nindent 4 }}
