# INTEL CONFIDENTIAL
#
# Copyright 2020-2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

apiVersion: v1
description: Intel® QuickAssist Technology (QAT) device plugin for Kubernetes
name: intel-qat-plugin
version: 0.23.0
sources:
- https://github.com/intel/intel-device-plugins-for-kubernetes.git
appVersion: 0.23.0
