# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.aas.name }}-config-pv
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  claimRef:
    name: {{ .Values.aas.name }}-config-pvc
    namespace: {{ .Values.aas.nameSpace }}
  nfs:
    path: {{ .Values.nfs.confPath }}
    server: {{ .Values.nfs.server }}
