# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.aas.name }}-config
  namespace: {{ .Values.aas.nameSpace }}
data:
  SAN_LIST: aas-svc.isecl.svc.cluster.local
  CMS_BASE_URL: https://cms-svc.isecl.svc.cluster.local:8445/cms/v1
  CMS_TLS_CERT_SHA384:
  AAS_DB_HOSTNAME: aasdb-svc.isecl.svc.cluster.local
  AAS_DB_PORT: "5432"
  AAS_DB_NAME: aasdb
  AAS_DB_SSLMODE: verify-full
  AAS_DB_SSLCERT: /etc/postgresql/server.crt
  NATS_ACCOUNT_NAME: 'ISecL-account'
  CREATE_CREDENTIALS: "true"
