# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.aas.name }}-deployment
  namespace: {{ .Values.aas.nameSpace }}
  labels:
    env: demo
    app: {{ .Values.aas.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.aas.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.aas.name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          name: {{ .Values.aas.name }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.aas.name }}-config
          ports:
            - containerPort: {{ .Values.aas.port }}
          volumeMounts:
            - name: aas-config-volume
              mountPath: /etc/authservice/
            - name: aas-logs-volume
              mountPath: /var/log/authservice/
            - name: aas-db-certs
              mountPath: /etc/postgresql/
            - mountPath: /etc/secrets/
              name: aas-secrets
              readOnly: true              
      volumes:
        - name: aas-config-volume
          persistentVolumeClaim:
            claimName: aas-config-pvc
        - name: aas-logs-volume
          persistentVolumeClaim:
            claimName: aas-logs-pvc
        - name: aas-db-certs
          secret:
            secretName: aas-db-certs
            defaultMode: 0640
        - name: aas-secrets
          projected:
            sources:
              - secret:
                  name: aas-credentials
              - secret:
                  name: aas-bootstrap-token
            
