# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.aas.name }}-logs-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  claimRef:
    name: {{ .Values.aas.name }}-logs-pvc
    namespace: {{ .Values.aas.nameSpace }}
  nfs:
    path: {{ .Values.nfs.logPath }}
    server: {{ .Values.nfs.server}}
