# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: check if host is controller
  debug:
    msg: "NFD is only for controller/k8s master host"
  when: "'controller_group' not in group_names"

- block:
    - include_tasks: nfd.yml
      when: not sgx_enabled or ansible_os_family == "RedHat"

    - include_tasks: sgx_nfd.yml
      when: sgx_enabled and ansible_os_family == "Debian"
  when: "'controller_group' in group_names"
