# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: check if prometheus-statsd-exporter already exists
  command: helm status statsd-exporter -n {{ telemetry_namespace }}
  ignore_errors: true
  changed_when: false
  register: get_statsd_exporter

- name: install prometheus-statsd-exporter chart
  block:
    - name: create certificates for Statsd-exporter
      include_role:
        name: kubernetes/certs
      vars:
        tls_secret_name: "{{ _proxy_secret_name }}"
        desired_namespace: "{{ telemetry_namespace }}"
        dns_names: ['statsd-exporter']
    - name: create temporary directory
      tempfile:
        state: directory
        suffix: prometheus-statsd-exporter
      register: tmp_dir

    - name: template values.yml to tmp directory
      template:
        src: values.yml.j2
        dest: "{{ tmp_dir.path }}/values.yml"
        mode: a=r,u+w

    - name: create prometheus-statsd-exporter chart template directory
      file:
        name: "{{ item }}"
        state: directory
        mode: a=rx,u+w
      loop:
        - "{{ _statsd_exporter_chart_dir }}"
        - "{{ _statsd_exporter_chart_dir }}/templates"

    - name: download prometheus-statsd-exporter chart
      get_url:
        url: "{{ _statsd_exporter_chart_url }}/{{ item }}"
        dest: "{{ _statsd_exporter_chart_dir }}"
        mode: a=rw
      register: result
      retries: "{{ number_of_retries }}"
      until: result is succeeded
      delay: "{{ retry_delay }}"
      loop: "{{ _statsd_exporter_chart }}"

    - name: create destination directories
      file:
        state: directory
        path: "{{ _statsd_exporter_chart_dir }}/{{ item | dirname }}"
        mode: a=rx,u+w
      loop: "{{ _statsd_exporter_chart_templates }}"

    - name: download prometheus-statsd-exporter chart templates
      get_url:
        url: "{{ _statsd_exporter_chart_url }}/{{ item }}"
        dest: "{{ _statsd_exporter_chart_dir }}/{{ item }}"
      register: result
      retries: "{{ number_of_retries }}"
      until: result is succeeded
      delay: "{{ retry_delay }}"
      loop: "{{ _statsd_exporter_chart_templates }}"

    - name: copy statsd-exporter files
      copy:
        src: "{{ item }}"
        dest: "{{ _statsd_exporter_chart_dir }}/templates/{{ item }}"
        mode: preserve
      loop: "{{ _statsd_exporter_files }}"

    - name: find backup files
      find:
        paths: "{{ _statsd_exporter_chart_dir }}/templates"
        patterns: "*.orig"
        recurse: true
      register: backup_files

    - name: remove backup files
      file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ backup_files.files }}"
      changed_when: true

    - name: install prometheus-statsd-exporter release
      command: "helm install statsd-exporter --namespace {{ telemetry_namespace }} -f {{ tmp_dir.path }}/values.yml {{ _statsd_exporter_chart_dir }}"
      changed_when: true

    - name: remove temporary directory
      file:
        path: "{{ tmp_dir.path }}"
        state: absent
      when: tmp_dir.path is defined
  when: get_statsd_exporter.rc != 0
