# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---

- name: 'disable sctp module on host'
  modprobe:
    name: sctp
    state: absent

- name: 'Create directory for helm chart values'
  file:
    path: '{{ cera_charts_path }}{{ app_name }}'
    state: directory
    mode: a=rx,u+w
    recurse: true

- name: 'Copy helm chart to host'
  copy:
    src: '{{ _edgeapps_git_repo.dest }}/network-functions/core-network/charts/amf-smf/'
    dest: '{{ cera_charts_path }}{{ app_name }}/'
    mode: preserve
    backup: false

- name: 'Copy helm chart values to host'
  template:
    src: 'values.yaml.j2'
    dest: '{{ cera_charts_path }}{{ app_name }}/values.yaml'
    mode: preserve
    backup: false

- name: Create AMF/SMF configuration script directory
  file:
    path: "{{ config_5gc_script_path }}"
    state: directory
    mode: a=rwx
  become: yes

- name: Copy script AMF/SMF configuration script to the remote
  copy:
    src: "update_amf_smf_configs.py"
    dest: "{{ config_5gc_script_path }}"
    mode: preserve

- name: '{{ app_name }} deployment'
  include_role:
    name: applications/common/cera_harbor_registry
  vars:
    - name: '{{ app_name }}'
    - tag: '{{ image_tag }}'
    - docker_file: '{{ _edgeapps_git_repo.dest }}/network-functions/core-network/5G/AMF_SMF/'
    - binaries: '{{ amf_smf_binaries_path }}'
    - docker_tar_image_path: '{{ amf_smf_docker_image_path }}'
    - docker_image_source: '{{ amf_smf_docker_image_source }}'
