# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---

- name: copy requirements.txt
  copy:
    src: "{{ _docker_requirements_file }}"
    dest: /tmp/requirements.txt
    mode: preserve

- name: install dependencies and docker-compose
  pip:
    requirements: /tmp/requirements.txt
    state: present
    executable: pip2
  register: result
  retries: "{{ number_of_retries }}"
  until: result is succeeded
  delay: "{{ retry_delay }}"
  become: yes
