# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

---
- name: get runc version
  shell: set -o pipefail && runc --version | grep -oP '{{ _docker_runc_ver_pattern }}\K(.+)'
  register: runc_rc_ver
  failed_when: false
  changed_when: false

# Upgrade runc to v1.0.0-rc93 which fixes an issue of freezing/frozen cgroups.
- name: upgrade runc to a fixed version
  block:
    - name: backup old runc
      copy:
        src: /usr/bin/runc
        dest: /usr/bin/runc_bak
        mode: preserve
        remote_src: true
      become: yes
    - name: download specific runc
      get_url:
        url: "{{ _docker_runc_url }}"
        dest: /usr/bin/runc
        checksum: "sha256:{{ _docker_runc_checksum }}"
      become: yes
  when: runc_rc_ver.rc == 0 and runc_rc_ver.stdout|int < _docker_runc_min_rc
