# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: include docker registry vars
  include_vars: ../../../harbor_registry/controlplane/defaults/main.yml

- name: clone Intel Device Plugins repository
  git:
    repo: "{{ _qat_dp.git_url }}"
    version: "{{ _qat_dp.git_ref }}"
    dest: "{{ _qat_dp.dir }}"
    force: true

- name: build Intel QAT Device Plugin image
  make:
    target: intel-qat-plugin
    chdir: "{{ _qat_dp.dir }}"

- name: tag Intel QAT Device Plugin image
  command: >
    docker tag intel/intel-qat-plugin:{{ _qat_dp.version }}
    {{ _qat_dp.image }}:{{ _qat_dp.version }}
  become: yes
  changed_when: true

- name: push Intel QAT Device Plugin image to local registry
  command: docker push {{ _qat_dp.image }}:{{ _qat_dp.version }}
  changed_when: true

- name: copy Helm chart to the controller node
  copy:
    src: "{{ role_path }}/charts/intel-qat-plugin"
    dest: "{{ ne_helm_charts_default_dir }}"
    mode: a=rw

- name: Template values for QAT Device Plugin
  template:
    src: "values.yml.j2"
    dest: "{{ ne_helm_charts_default_dir }}/intel-qat-plugin/values.yml"
    force: true
    mode: a=rw

- name: install Intel QAT Plugin Helm chart
  command: >
    helm upgrade -i intel-qat-plugin
    -f {{ ne_helm_charts_default_dir }}/intel-qat-plugin/values.yml
    --namespace {{ _qat_dp.namespace }}
    {{ ne_helm_charts_default_dir }}/intel-qat-plugin
  changed_when: true
