# INTEL CONFIDENTIAL
#
# Copyright 2020-2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
# This file contains variables intended to be configured by user.
# It allows feature enabling and configuration.
# Per-host variables should be places in `host_vars` directory.
# Features should not be configured by changing roles' defaults (i.e. role/defaults/main.yml)

##################################################
##### User settings

### GitHub token
# It must be provided when using private repositories.
# Not required when using github.com/open-ness repositories.
# How to create a GitHub token: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
git_repo_token: ""

##################################################

##### Network Edge

### Edge Services Git Repository
_edge_services_git_repo:
  url: https://github.com/smart-edge-open/edge-services.git
  download_dir: "{{ project_dir }}/edgeservices"
  branch: smart-edge-open-22.04

# If True, the repository will be deleted and cloned again
# If False, repository will be left as it is and any changes won't be overwritten.
always_clean_repository: true

## Edge Agents Git Repository
_edge_agents_git_repo:
  url: https://github.com/smart-edge-open/edge-agents.git
  download_dir: "{{ project_dir }}/edge-agents"
  branch: smart-edge-open-22.04

## Network Policies for 5GC traffic
network_policies_enable: false

# OpenNESS Harbor registry variables
docker_registry_port: 30003
openness_harbor_registry_ip: "{{ ansible_default_ipv4.address | default(ansible_all_ipv4_addresses[0]) }}"
openness_harbor_registry_address: "{{ openness_harbor_registry_ip }}:{{ docker_registry_port }}/intel"

# Deploy OpenNESS services
openness_enable: true #required for EdgeDNS
## Edge DNS
dns_enable: true

# OpenNESS pods retry variable
openness_pods_timeout_min: 15
