# INTEL CONFIDENTIAL
#
# Copyright 2019-2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
- name: certificate for EdgeDNS CLI
  block:
    - name: create directory for EdgeDNS client certificate
      file:
        name: "{{ _certs_dest }}/client"
        state: directory
        mode: a=rwx
    - name: create EdgeDNS client certificate
      command: "{{ project_dir }}/scripts/tls_pair.sh edgedns.smartedge {{ _certs_dest }}/client {{ _smartedge_rootCA }}/CA"
      become: yes
    - name: create symbolic link to root's cert
      file:
        src: "{{ _smartedge_rootCA }}/CA/cert.pem"
        dest: "{{ _certs_dest }}/client/root.pem"
        state: link
    - name: set CA private key mode
      file:
        path: "{{ _certs_dest }}/client/key.pem"
        mode: a=,u=rw
      become: yes
