# INTEL CONFIDENTIAL
#
# Copyright 2019-2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---

- name: install spire
  command: kubectl apply -k "{{ _nsm_git_repo_url }}/examples/spire?ref={{ _nsm_version }}"
  changed_when: true

- name: wait for spire-agent and spire-server to start
  command: >
    kubectl wait -n spire --timeout=1m --for=condition=ready pod -l \
    "app in ( spire-agent,spire-server )"
  changed_when: false

- name: install nsm
  block:
  - name: create nsm namespace if not present
    include_role:
      name: baseline_ansible/kubernetes/custom_namespace
    vars:
      - _custom_ns: [ nsm-system ]

  - name: apply nsm resources
    command: kubectl apply -k "{{ _nsm_git_repo_url }}/examples/basic?ref={{ _nsm_version }}"
    changed_when: true

  - name: wait for nsm to start
    command: >
      kubectl wait pod -l "app in (admission-webhook-k8s,forwarder-vpp,nsmgr,registry-k8s)" \
      --for=condition=ready -n nsm-system --timeout=20s
    register: nsm_started
    retries: 30
    until: nsm_started.rc == 0
    changed_when: false
