# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
- name: download modules for kube-cnca plugin
  shell: source /etc/profile && go mod download
  args:
    chdir: "{{ _epcforedge_git_repo.download_dir }}/cnca/cli"
  register: result
  retries: "{{ number_of_retries }}"
  until: result is succeeded
  delay: "{{ retry_delay }}"
  changed_when: true

- name: get istio gateway endpoints
  block:
    - name: get gateway ip addr
      shell: >
        (kubectl get po -l istio=ingressgateway -n istio-system -o jsonpath='{.items[0].status.hostIP}')
      register: gateway_ip_out
    - name: register ingress gateway ip addr on master node
      set_fact:
        gateway_ip: "{{ gateway_ip_out.stdout }}"
    - name: get gateway port
      shell: >
        (kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="https")].nodePort}')
      register: gateway_port_out
    - name: register port_num on master node
      set_fact:
        gateway_port: "{{ gateway_port_out.stdout }}"
    - name: delete dns entry of af istio gateway from hosts file
      command: sed -i '/afservice/d' /etc/hosts
      args:
        warn: false
      failed_when: false
      become: yes
    - name: delete dns entry of oam istio gateway from hosts file
      command: sed -i '/oamservice/d' /etc/hosts
      args:
        warn: false
      failed_when: false
      become: yes
    - name: update hosts file for dns resolution
      shell: >
        echo -e "{{ gateway_ip }}\tafservice.ngc oamservice.ngc" >> /etc/hosts
      become: yes
  when: ne_istio_enable | default(false)

- name: build kube-cnca plugin
  shell: source /etc/profile && go build -ldflags "-X cnca.HTTP2ClientTLSCAPath={{ _certs_dest }}/ngc" -o "{{ _cnca_plugin_name }}"
  args:
    chdir: "{{ _epcforedge_git_repo.download_dir }}/cnca/cli"
  changed_when: true

- name: build kube-cnca plugin with istio gateway configuration
  shell: >
      source /etc/profile && go build -ldflags "-X cnca.HTTP2ClientTLSCAPath={{ _certs_dest }}/ngc
      -X cnca.GatewayPort={{ gateway_port }}" -o "{{ _cnca_plugin_name }}"
  args:
    chdir: "{{ _epcforedge_git_repo.download_dir }}/cnca/cli"
  when: ne_istio_enable | default(false)

- name: install kube-cnca plugin
  command: mv "{{ _cnca_plugin_name }}" "{{ _cnca_plugin_dest }}"
  args:
    chdir: "{{ _epcforedge_git_repo.download_dir }}/cnca/cli"
  changed_when: true
  become: yes
