# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---

- name: fetch VFs pci addresses for a PF
  shell: "for vf in /sys/class/net/{{ pfname }}/device/virtfn*;do basename $(readlink -f $vf);done"
  register: vf_pciids
  args:
    executable: /bin/bash
  changed_when: false

- name: store VFs PCI addresses in fact
  set_fact:
    vfs_pcis: "{{ vfs_pcis | default({}) | combine( { pfname: vf_pciids.stdout_lines } ) }}"
