# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
- name: online mode
  block:
    - name: print debug message
      debug:
        msg:
          - "Using git token for repository checkout"
      when: git_repo_token|length > 0

    - name: checkout clean ido-epcforedge repository
      git:
        repo: "{{ _epcforedge_git_repo.dir }}"
        dest: "{{ _epcforedge_git_repo.download_dir }}"
        version: "{{ _epcforedge_git_repo.branch }}"
        force: true
      register: result
      retries: "{{ number_of_retries }}"
      until: result is succeeded
      delay: "{{ retry_delay }}"
