# INTEL CONFIDENTIAL
#
# Copyright 2020-2020 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---

- name: Create Cera scripts folder
  file:
    path: "{{ cera_scripts_path }}"
    state: directory
    mode: a=rx,u+w

- name: Copy script files
  template:
    src: "{{ item }}.j2"
    dest: "{{ cera_scripts_path }}/{{ item }}"
    mode: a+x
  loop:
    - "start_l1.sh"
    - "start_cu.sh"
    - "start_du.sh"
    - "stop_gnb.sh"
    - "turbo.sh"

- name: Start turbo script  # noqa command-instead-of-shell
  shell: "./turbo.sh"
  args:
    chdir: "{{ cera_scripts_path }}"
  changed_when: false
  become: yes

- name: Start l1 app  # noqa command-instead-of-shell
  shell: "./start_l1.sh"
  args:
    chdir: "{{ cera_scripts_path }}"
  changed_when: false

- name: Start CU app  # noqa command-instead-of-shell
  shell: "./start_cu.sh"
  args:
    chdir: "{{ cera_scripts_path }}"
  changed_when: false

- name: Start DU app  # noqa command-instead-of-shell
  shell: "./start_du.sh"
  args:
    chdir: "{{ cera_scripts_path }}"
  changed_when: false
