# INTEL CONFIDENTIAL
#
# Copyright 2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
_rook_ceph_main_dir: "{{ project_dir }}/rook_ceph"
_rook_ceph_files_dir: "{{ project_dir }}/rook_ceph/files"

_crds_url: "https://raw.githubusercontent.com/rook/rook/{{ _rook_ceph_version }}/cluster/examples/kubernetes/ceph/crds.yaml"
_common_url: "https://raw.githubusercontent.com/rook/rook/{{ _rook_ceph_version }}/cluster/examples/kubernetes/ceph/common.yaml"
_operator_url: "https://raw.githubusercontent.com/rook/rook/{{ _rook_ceph_version }}/cluster/examples/kubernetes/ceph/operator.yaml"
_toolbox_url: "https://raw.githubusercontent.com/rook/rook/{{ _rook_ceph_version }}/cluster/examples/kubernetes/ceph/toolbox.yaml"

_rook_ceph_version: "release-1.7"
_rook_ceph_limits:
  api:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  mgr:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  mon:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  osd:
    requests:
      cpu: "500m"
      memory: "4Gi"
    limits:
      cpu: "500m"
      memory: "4Gi"

