#!/bin/bash
# INTEL CONFIDENTIAL
#
# Copyright 2020-2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.


BASEDIR=$(dirname "$0")
echo "$BASEDIR"

TIMEOUT=300
NS=${NS:-$PWEKNS}

ranf=$(kubectl -n $NS get rans.pwek.smart.edge.org common -o json | jq .spec)
DUS=$(jq -r .ndu <<< $ranf)

function check_helm_status {
  expire=$(( $(date +%s) + TIMEOUT ))
  while true
  do
    status=$(helm status -n "$1" "$2" -o json 2>/dev/null | jq -r .info.status)
    if [ -z "$status" ]; then
      echo "Can not get status of $2 in $1 namespace, exit."
      return 0
    else
      echo "$2 status: $status"
    fi

    sleep 1
    if [ "$(date +%s)" -ge $expire ]; then
      echo "Timeout $TIMEOUT, status of $2 is still: $status, maybe something wrong with the system"
      return 1
    fi
  done
}

CHART=vdu
echo "helm uninstall $CHART -n $NS"
helm uninstall $CHART -n $NS
check_helm_status $NS $CHART
{ ERROR=$(helm status -n $NS $CHART 2>&1 1>&$out); } {out}>&1
sed "s/Error: release: \(not found\)/Info: release $CHART: \1/" <<< $ERROR

for i in $(seq 2 $DUS); do
  CHART=vdu${i}
  echo "helm uninstall $CHART -n $NS"
  helm uninstall $CHART -n $NS
  check_helm_status $NS $CHART
  { ERROR=$(helm status -n $NS $CHART 2>&1 1>&$out); } {out}>&1
  sed "s/Error: release: \(not found\)/Info: release $CHART: \1/" <<< $ERROR
done

CHART=vcu
echo "helm uninstall -n $NS $CHART"
helm uninstall -n $NS $CHART
check_helm_status $NS $CHART
{ ERROR=$(helm status -n $NS $CHART 2>&1 1>&$out); } {out}>&1
sed "s/Error: release: \(not found\)/Info: release $CHART: \1/" <<< $ERROR
