# INTEL CONFIDENTIAL
#
# Copyright 2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---

- name: verify kubevirt deployments
  check_k8s_object:
    name: "{{ item }}"
    namespace: kubevirt
    kind: deployment
  loop:
  - virt-api
  - virt-controller
  - virt-operator

- name: verify cdi deployments
  check_k8s_object:
    name: "{{ item }}"
    namespace: cdi
    kind: deployment
  loop:
  - cdi-apiserver
  - cdi-deployment
  - cdi-operator
  - cdi-uploadproxy
