# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.aasDB.name }}-credentials
  namespace: {{ .Values.aasDB.nameSpace }}
stringData:
  AAS_DB_USERNAME: aasdbuser
  AAS_DB_PASSWORD: aasdbpassword
