# Copyright (C) 2021  Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.aasDB.appName }}-svc
  namespace: {{ .Values.aasDB.nameSpace }}
  labels:
    app: {{ .Values.aasDB.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.aasDB.port }}
      targetPort: {{ .Values.aasDB.port }}
  selector:
    app: {{ .Values.aasDB.appName }}
