# INTEL CONFIDENTIAL
#
# Copyright 2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
- name: create temporary custom .openness_gitconfig
  include_tasks: "{{ _gitconfig_bootstrap_path }}"

- block:
  - name: download modules for certsigner
    shell: source /etc/profile && go mod download
    args:
      chdir: "{{ _edge_services_git_repo.download_dir }}/cmd/certsigner"
    register: result
    retries: "{{ number_of_retries }}"
    until: result is succeeded
    delay: "{{ retry_delay }}"

  - name: download modules for certrequester
    shell: source /etc/profile && go mod download
    args:
      chdir: "{{ _edge_services_git_repo.download_dir }}/cmd/certrequester"
    register: result
    retries: "{{ number_of_retries }}"
    until: result is succeeded
    delay: "{{ retry_delay }}"

  - name: build binaries and images for certsigner
    shell: source /etc/profile && make certsigner
    args:
      chdir: "{{ _edge_services_git_repo.download_dir }}"

  - name: build binaries and images for certrequester
    shell: source /etc/profile && make certrequester
    args:
      chdir: "{{ _edge_services_git_repo.download_dir }}"

  always:
    - name: remove .openness_gitconfig
      include_tasks: "{{ _gitconfig_remove_path }}"
  when: cert_enabled

# since these pods are part of openness' Deployment will be recreated after deletion
# this step is for pods to use newly created docker images from previous block
- name: recreate openness pods
  shell: >
    set -o pipefail &&
    kubectl delete --namespace={{ system_namespace }} $(kubectl get pods --namespace={{ system_namespace }}
    --field-selector spec.nodeName={{ node_name }} -o=NAME | grep -E 'certsigner' )
  delegate_to: "{{ groups['controller_group'][0] }}"
  failed_when: false
  changed_when: true
