# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---

- name: Create /etc/ihub/
  file: 
    path: "/etc/ihub/"
    state: directory
    owner: "{{ project_user }}"
    group: "{{ project_group }}"
    mode: a=rx,u+w
  become: yes

- name: Deploy isecl ihub
  command: "./isecl-bootstrap-helm.sh up ihub"
  args:
    chdir: "{{ isecl_helm_charts_dir }}"
  environment:
    BEARER_TOKEN: "{{ isecl_install_admin_bearer_token }}"
    CMS_TLS_CERT_SHA384: "{{ isecl_cms_tls_hash }}"
  changed_when: false
