# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
- name: Copy create_k8s_extsched_certs.sh
  copy:
    src: "{{ isecl_build_dir }}/utils/build/k8s-manifests/k8s-extensions-scheduler/scripts/create_k8s_extsched_certs.sh"
    dest: "{{ isecl_helm_charts_dir }}/k8s-extensions-scheduler/scripts/"
    remote_src: yes
    mode: preserve

- name: Copy iHub certificate
  copy:
    src: "{{ isecl_nfs_client_mount_path }}/isecl/ihub/config/ihub_public_key.pem"
    dest: /etc/ihub/
    remote_src: yes
    mode: preserve
  become: yes

- name: Create isecl-k8s-extensions folder
  file: 
    path: "{{ isecl_k8s_extensions }}"
    state: directory
    mode: a=rx,u+w

- name: Update isecl_k8s_extensions folder in charts
  replace:
    path: "{{ isecl_helm_charts_dir }}/k8s-extensions-scheduler/values.yaml"
    regexp: "<isecl_k8s_extensions>"
    replace: "{{ isecl_k8s_extensions }}"

- name: Deploy isecl isecl-scheduler
  command: "./isecl-bootstrap-helm.sh up isecl-scheduler"
  args:
    chdir: "{{ isecl_helm_charts_dir }}"
  environment:
    BEARER_TOKEN: "{{ isecl_install_admin_bearer_token }}"
    CMS_TLS_CERT_SHA384: "{{ isecl_cms_tls_hash }}"
    ISECL_K8S_EXTENSIONS: "{{ isecl_k8s_extensions }}"
    PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/go/bin"
  become: yes
  changed_when: false

- name: Copy scheduler-policy
  copy:
    src: "{{ isecl_build_dir }}/utils/build/k8s-manifests/k8s-extensions-scheduler/config/scheduler-policy.json"
    dest: "{{ isecl_k8s_extensions }}/"
    remote_src: yes
    mode: preserve

- name: Generate kube-scheduler patch
  template:
    src: extensions-scheduler-patch.yml.j2
    dest: "/etc/kubernetes/manifests/extensions-scheduler-patch.yml"
    mode: a=rx,u+w
  become: yes

- name: Copy kustomization.yml
  copy:
    src: "kube-scheduler-ext/kustomization.yml"
    dest: "/etc/kubernetes/manifests/"
    mode: preserve
  become: yes

- name: Apply kube-scheduler patch
  command: kubectl kustomize . -o kube-scheduler.yaml
  args:
    chdir: "/etc/kubernetes/manifests/"
  changed_when: false
  become: yes

- name: Restart kubelet service
  service:
    name: kubelet
    state: restarted
  become: yes
