# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
- name: Update TA agent SAN list
  replace:
    path: "{{ isecl_helm_charts_dir }}/trust-agent/values.yaml"
    regexp: "<ta-agent-san-list>"
    replace: "{{ isecl_k8s_control_plane_ip }},{{ isecl_k8s_control_plane_hostname }}"

- name: Add msr module
  modprobe:
    name: msr
    state: present
  become: yes

- name: Deploy isecl trust-agent
  command: "./isecl-bootstrap-helm.sh up tagent"
  args:
    chdir: "{{ isecl_helm_charts_dir }}"
  environment:
    BEARER_TOKEN: "{{ isecl_install_admin_bearer_token }}"
    CMS_TLS_CERT_SHA384: "{{ isecl_cms_tls_hash }}"
    CC_TA_TOKEN: "{{ isecl_custom_claims_admin_bearer_token }}"
  changed_when: false
