# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

apiVersion: v1
description: Intel® QuickAssist Technology (QAT) device plugin for Kubernetes
name: intel-qat-plugin
version: 0.17.0
sources:
- https://github.com/intel/intel-device-plugins-for-kubernetes.git
appVersion: 0.17.0
