# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.cms.name }}-config-pvc
  namespace: {{ .Values.cms.nameSpace }}
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 128Mi
