# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.cms.name }}-config
  namespace: {{ .Values.cms.nameSpace }}
data:
  SAN_LIST: cms-svc.isecl.svc.cluster.local
  AAS_TLS_SAN: aas-svc.isecl.svc.cluster.local
  AAS_API_URL: https://aas-svc.isecl.svc.cluster.local:8444/aas/v1
