# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.cms.name }}-svc
  namespace: {{ .Values.cms.nameSpace }}
  labels:
    env: test
    app: {{ .Values.cms.name }}
spec:
  selector:
    app: {{ .Values.cms.name }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.cms.port }}
      targetPort: {{ .Values.cms.port }}
      nodePort: {{ .Values.service.nodePort }}


