# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

{{- if .Values.upgradeConfig.enabled -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.basename }}-upgrade
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.basename}}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.basename}}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Never
      containers:
        - name: {{ .Values.basename }}
          {{- toYaml .Values.upgradeConfig.container | nindent 10 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{- toYaml .Values.upgradeConfig.environment | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.basename }}-config
          volumeMounts:
            - name: hvs-config-volume
              mountPath: {{ .Values.volumeConfig.hvsConfigPath }}
            - name: hvs-logs-volume
              mountPath: {{ .Values.volumeConfig.hvsLogsPath }}
            - name: hvs-db-certs
              mountPath: {{ .Values.volumeConfig.hvsDbCertsPath }}
      volumes:
        - name: hvs-logs-volume
          persistentVolumeClaim:
            claimName: hvs-logs-pvc
        - name: hvs-config-volume
          persistentVolumeClaim:
            claimName: hvs-config-pvc
        - name: hvs-db-certs
          secret:
            secretName: hvs-db-certs
            defaultMode: 0640

...
{{- end }}
