# INTEL CONFIDENTIAL
#
# Copyright 2021-2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---

- hosts: controller_group
  any_errors_fatal: true

  pre_tasks:
    - name: set node name
      set_fact: node_name={{ ansible_nodename | lower }}

  roles:
    - role: applications/openness/controlplane
      when: openness_enable | default(True)

    - role: applications/ngc/controlplane
      when: ne_ngc_enable | default(False)

    - role: applications/common/cera_namespace
      when: cera_namespace_enable | default(False)
    - role: applications/common/pwek_namespace
      when: pwek_namespace_enable | default(False)
    - role: applications/common/cera_charts_path
      when: cera_charts_path_enable | default(False)
    - role: applications/i_upf
      when: i_upf_enable | default(False)
    - role: applications/psa_upf
      when: psa_upf_enable | default(False)
    - role: applications/amf_smf
      when: amf_smf_enable | default(False)
    - role: applications/remote_dn
      when: remote_dn_enable | default(False)
    - role: applications/pwek_5gc
      when: pwek_5gc_enable | default(False)
    - role: applications/gnodeb
      when: gnodeb_enable | default(False)

- hosts: edgenode_group
  any_errors_fatal: true
  
  roles:
    - role: applications/pwek_gnodeb
      when: pwek_gnodeb_enable | default(False)

- hosts: localhost
  any_errors_fatal: true
  roles:
    - role: applications/eis_deploy
      when: edgeapps_deployment_enable | default(False) and deploy_demo_app == "eis"

- hosts: controller_group
  any_errors_fatal: true

  pre_tasks:
    - name: set node name
      set_fact: node_name={{ ansible_nodename | lower }}

  roles:
    - role: applications/local_dn
      when: edgeapps_deployment_enable | default(False) and deploy_demo_app == 'eis'
