# INTEL CONFIDENTIAL
#
# Copyright 2021-2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---

- hosts: controller_group
  any_errors_fatal: true

  pre_tasks:
    - name: set node name
      set_fact: node_name={{ ansible_nodename | lower }}

  roles:
    - role: applications/openness/controlplane
      when: openness_enable | default(True)
    - role: applications/common/pwek_namespace
      when: pwek_namespace_enable | default(False)
    - role: applications/pwek_5gc
      when: pwek_5gc_enable | default(False)
    - role: applications/pwek_common
      when: pwek_common_enable | default(False)

- hosts: edgenode_group
  any_errors_fatal: true

  pre_tasks:
  - name: set node name
    set_fact: node_name={{ ansible_nodename | lower }}
  
  roles:
    - role: applications/openness/node
      when: openness_enable | default(True)
    - role: applications/pwek_gnodeb
      when: pwek_gnodeb_enable | default(False)
    - role: applications/pwek_firewalld
      when: pwek_enable_firewalld | default(False)
    # ESP is executing deployment sequentially: first controller node then worker node.
    # The applications/pwek_vendor role must be run on controller, but after node is ready.
    # It is delegated from worker to controller and should be run only once in case more worker nodes in configuration.
    - role: applications/pwek_vendor
      when: pwek_vendor_enable | default(False)
      delegate_to: "{{ groups['controller_group'][0] }}"
      run_once: true
