# INTEL CONFIDENTIAL
#
# Copyright 2021-2021 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---

- hosts: localhost
  roles:
    - role: baseline_ansible/infrastructure/git_repo
      vars:
        git_repo_url: "{{ _edgeapps_git_repo.dir }}"
        git_repo_dest: "{{ _edgeapps_git_repo.dest }}"
        git_repo_branch: "{{ _edgeapps_git_repo.branch }}"
        ansible_user: "{{ lookup('env', 'USER') }}"
      when: edgeapps_repo_enable | default(False)

- hosts: controller_group
  any_errors_fatal: true
  roles:
    - role: infrastructure/epc_git_repo
      when: ne_ngc_enable | default(False)
    - role: infrastructure/set_cn_interfaces
      when: set_core_network_interfaces | default(False)
    - role: infrastructure/set_gnb_interfaces
      when: set_gnodeb_interfaces | default(False)

- hosts: edgenode_group
  any_errors_fatal: true
  roles:
    - role: infrastructure/pwek_kernel_config
      when: pwek_enable | default(False)
    - role: infrastructure/build_pwek_dpdk
      when: pwek_enable | default(False)
    - role: infrastructure/pwek_debug_files/node
      when: pwek_enable | default(False)
