# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021 Intel Corporation

# Default values for hvs-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: isecl

basename: hvs

image:
  repository: isecl/hvs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v4.1.0"

podAnnotations: {}

podSecurityContext:
  # fsGroup: 2000
  fsGroup: 1001

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  runAsUser: 1001
  runAsGroup: 1001

service:
  type: NodePort
  port: 8443
  targetPort: 8443
  nodePort: 30443

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    storage: 1Gi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

hvsConfiguration:
  AAS_API_URL: https://aas-svc.isecl.svc.cluster.local:8444/aas/v1
  CMS_BASE_URL: https://cms-svc.isecl.svc.cluster.local:8445/cms/v1
  CMS_TLS_CERT_SHA384:
  SAN_LIST: hvs-svc.isecl.svc.cluster.local
  HVS_DB_HOSTNAME: hvsdb-svc.isecl.svc.cluster.local
  HVS_DB_NAME: hvsdb
  HVS_DB_SSLCERT: /etc/postgresql/server.crt
  HVS_DB_PORT: "5432"
  HVS_DB_SSLMODE: verify-full
  NATS_SERVERS: ""

persistentVolumeConfig:
  storageClassName: nfs
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    confPath: <nfs-client-mount-path>/isecl/hvs/config
    logsPath: <nfs-client-mount-path>/isecl/hvs/logs
    server: <nfs-server-ip/nfs-server-hostname>
  requests:
      storage: 128Mi
  logStorage: 1Gi

volumeConfig:
  hvsConfigPath: /etc/hvs/
  hvsLogsPath: /var/log/hvs/
  hvsDbCertsPath: /etc/postgresql/
  hvsSecretsPath: /etc/secrets/

upgradeConfig:
  enabled: false
  container:
    image: <upgrade-image-name>:<image-tag>
    command: ["/container_upgrade.sh"]
    imagePullPolicy: Always
  environment:
    - name: CONFIG_DIR
      value: "/etc/hvs"
    - name: COMPONENT_VERSION
      value: <current deployed version>
