# INTEL CONFIDENTIAL
#
# Copyright 2020-2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gnbfrequencies.pwek.smart.edge.org
spec:
  group: pwek.smart.edge.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                absFreqPointA:              # absFreqPointA
                  type: integer
                  minimum: 0
                  maximum: 100000000
                  default: 3700560
                absArfcnPointA:              # absArfcnPointA
                  type: integer
                  minimum: 0
                  maximum: 10000000
                  default: 646704
                nrFreqBand:                  # Indicates the number of nr frequence band
                  type: integer
                  minimum: 0
                  maximum: 10000
                  default: 78
                offsetToCarrier:             # Indicates the offset of carrier
                  type: integer
                  minimum: 0
                  maximum: 10000
                  default: 0
                carrierBw:                   # For both UL and DL.
                  type: integer
                  minimum: 0
                  maximum: 10000
                  default: 273
                subCarrierSpacing:           # Indicates the sub carrier spacing, default is KHz30
                  type: string
                  default: KHz30
                bSChannelBw:                 # Indicates the BS Channel bandwidth. Both for DL ad UL.
                  # type: integer
                  type: string
                  default: 100MHZ
                earfcn:                      # both for DL ad UL
                  type: integer
                  minimum: 0
                  maximum: 10000000
                  default: 649980
                pMaxUl:                      # UL, default is 23
                  type: integer
                addtionalSpectrumEmissionUl: # UL, default is 0
                  type: integer
                freqShft7p5khzUl:            # UL, default is 7P5KHZ_DISBL
                  type: string
                absFreqSsbDl:                # only for DL, default is 3708480
                  type: integer
                absArfcnSsbDl:               # only for DL, default is 3708480
                  type: integer
  scope: Namespaced
  names:
    plural: gnbfrequencies
    singular: gnbfrequency
    kind: GnbFrequency
    shortNames:
      - freq
