# INTEL CONFIDENTIAL
#
# Copyright 2020-2022 Intel Corporation.
#
# This software and the related documents are Intel copyrighted materials, and your use of
# them is governed by the express license under which they were provided to you ("License").
# Unless the License provides otherwise, you may not use, modify, copy, publish, distribute,
# disclose or transmit this software or the related documents without Intel's prior written permission.
#
# This software and the related documents are provided as is, with no express or implied warranties,
# other than those that are expressly stated in the License.

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ssbmtcs.pwek.smart.edge.org
spec:
  group: pwek.smart.edge.org
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        # openAPIV3Schema is the schema for validating custom objects.
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                periodicity:
                  type: string
                  pattern: "^sf(5|10|20|40|80|160)"
                offset:
                  type: integer
                  minimum: 0
                  maximum: 159
                duration:
                  type: object
                  properties:
                    value:
                      type: integer
                      minimum: 0
                      maximum: 5
                    tomeasure:
                      type: string
                      pattern: "^[0-1]{0,63}$"
  scope: Namespaced
  names:
    plural: ssbmtcs
    singular: ssbmtc
    kind: SSBMTC
    shortNames:
      - smtc
